version: '3'
services:
  cod-application:
    container_name: cod-application
    image: cod-application
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "8080:80"
    healthcheck:
      test: wget localhost:8080/health -q -O - > /dev/null 2>&1
      interval: 60s
      timeout: 5s
      retries: 5
    depends_on: 
      - db
  db:
    container_name: cod-sqlserver
    image: cod-sqlserver
    build:
      context: docker/MsSql
      dockerfile: mssql.dockerfile
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"