version: '3'
services:
  cod-application:
    container_name: cod-application
    image: cod-application
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "8080:80"
    healthcheck:
      test: wget localhost:5000/ -q -O - > /dev/null 2>&1
      interval: 60s
      timeout: 5s
      retries: 5